name: CI

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer:v2

      - name: Run linter
        run: composer test

      - name: Install humbug/box
        run: composer phar:install-tools

      - name: Install dependencies
        run: composer install --prefer-dist --no-dev --no-interaction

      - name: Build phar
        run: composer phar:build

      - name: Upload phar to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ github.ref_name }} diffy.phar
