name: CI

on:
#  release:
#    types: [published]
  - push


jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer:v2

      - name: Run linter
        run: composer test

      - name: Install humbug/box
        run: composer phar:install-tools

      - name: Install dependencies
        run: composer install --prefer-dist --no-dev --no-interaction

      - name: Install build phar
        run: composer phar:build
